name: web app workflow
on:
    push:
        branches:
            - main
            - master
            - "feature/**"
    pull_request:
        branches:
            - main
            - master
            - "feature/**"
jobs:
    test_build-n:
        runs-on: ubuntu-latest
        steps:
            - name: check & clone code
              uses: actions/checkout@v5
            - name: setup node at vm 
              uses: actions/setup-node@v6
              with:
                  node-version: 24
            - name: install dependencies
              run: npm install      
        #   - name: run tests
        #     run: npm test
            - name: build project
              run: npm run build

